-- +goose Up

CREATE TABLE feeds(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    name CHARACTER VARYING(255) NOT NULL,
    url CHARACTER VARYING(255) NOT NULL UNIQUE,
    user_id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL
);


-- +goose Down
DROP TABLE feeds;
