-- +goose Up
CREATE TABLE posts(
    id UUID PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
    title CHARACTER VARYING(255) NOT NULL,
    url CHARACTER VARYING(255) NOT NULL UNIQUE,
    description CHARACTER VARYING(255),
    published_at TIMESTAMP WITH TIME ZONE,
    feed_id UUID REFERENCES feeds(id) ON DELETE CASCADE NOT NULL
);


-- +goose Down
DROP TABLE posts;
